Repository DUNE-DAQ/iomanager, pull requests merged in 2022-06, with the labels that each got.

#17 version nump
  CMakeLists.txt
Labels: version change

#20 Fix network callback to use noexcept API, change timeouts to 1 ms.
  include/iomanager/Receiver.hpp
Labels: bug

#23 Update README.md
  docs/README.md
Labels: documentation

#22 Drain remaining messages in callback before exiting.
  include/iomanager/Receiver.hpp
Labels: enhancement

#21 Move NetworkManager class from networkmanager package.
  CMakeLists.txt
  cmake/iomanagerConfig.cmake.in
  docs/NetworkManager.dia
  docs/NetworkManager.png
  include/iomanager/CommonIssues.hpp
  include/iomanager/IOManager.hpp
  include/iomanager/NetworkManager.hpp
  include/iomanager/Receiver.hpp
  include/iomanager/Sender.hpp
  schema/iomanager/connectioninfo.jsonnet
  src/NetworkManager.cpp
  unittest/NetworkManager_test.cxx
Labels: enhancement

#24 Update README.md, add initial version of NetworkManager.md
  docs/NetworkManager.md
  docs/README.md
Labels: documentation
